### ISSUE TITLE
How to filter which test/describe blocks are run

### ISSUE THREAD

**Issue by JohnAllen** [kvendrik/jest-lite#7]
Is there a way to filter which tests are run, by name? In general how can the CLI options be available to `jest-lite`?

Looked through the source and didn't really see a way.

**Comment by kvendrik** [comment]
The Jest CLI uses the options it receives to configure the underlaying packages. Because Jest Lite relies on those underlaying packages like Jest Circus directly its not as straight forward as passing in the options you would usually pass into the CLI.

If you need a specific CLI option I would suggest diving into the Jest CLI code to figure out what options they pass to the underlaying packages and mimic that.

I don't have plans to add as easier way to do this as I enjoy the simplicity of the current implementation but am open to receiving a PR that makes using the same options the CLI accepts a bit easier somehow.

As a quick fix you could also use [`it.only` and `describe.only`](https://jestjs.io/docs/en/api#testonlyname-fn-timeout).
